FROM python:3.7-bullseye

RUN mkdir /api

WORKDIR /api

ADD ./requirements.txt ./

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip \
    && python3 -m pip install --upgrade setuptools \
    && pip install -r requirements.txt

ADD ./ ./

CMD python manage.py migrate;gunicorn api.wsgi -b 0.0.0.0:8000 --reload --timeout 120 