FROM node:current-alpine3.11 AS npm-builder

ADD ./ /app
WORKDIR /app
RUN touch ./src/config.js; echo export const API_HOST=$'"'/api/$'"'$';' > ./src/config.js;

RUN set -x && \
    npm install && \
    npm run build

FROM node:current-alpine3.11
WORKDIR /app
RUN npm install -g serve
COPY --from=npm-builder /app/build .

CMD serve -s -l 80 .