# Generated by Django 3.1.2 on 2021-10-27 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211026_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator('^0\\d{9}$')]),
            preserve_default=False,
        ),
    ]
