# Generated by Django 3.1.2 on 2021-10-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('image', models.URLField(null=True)),
                ('description', models.CharField(max_length=2000)),
                ('source', models.CharField(max_length=50)),
                ('source_icon', models.URLField(null=True)),
            ],
        ),
    ]
