FROM python:3.7-bullseye

RUN mkdir /aggregator

WORKDIR /aggregator

ADD ./requirements.txt ./

RUN apt-get update && apt-get install -y cron

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip \
    && python3 -m pip install --upgrade setuptools \
    && pip install -r requirements.txt

ADD ./ ./

CMD env >> /etc/environment; (echo "@hourly /usr/local/bin/python /aggregator/aggregator.py >/proc/1/fd/1 2>/proc/1/fd/1") | crontab - ; cron -f -l 2;